version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - 5672:5672